name: "known-vertex-colour-fitting"
tag: "${filename:${data.mesh_path}}"
exp_root_dir: "outputs"
seed: 0

data_type: data.known-heat-vertex-colours
data:
  mesh_path: ../objects/spot/spot_triangulated.ply
  bake_vert_colours_if_textured: True
  merge_tex: True

  sample_all_vertices: True
  num_workers: 0

  source_sampling_method: fps

trainer_type: trainers.stationary-heat-kernels
trainer:
  tracer_type: modules.cpu-geodesic-tracer
  tracer: 
    n_debug_traces: 10

  eigen_albo: 
    k_eig: 256
    mesh_path: ${data.mesh_path}
    enable_distance_weighting: False

  model: 
    n_sources: 80
    kernel_dim: 3

    out_net: False
    normalize_colours: True

  optimizers:
    - name: Adam
      args:
        lr: 1e-3
      params:
        model._kernel_colours: {}
        model._angles: {}
        model._anisotropies: {}
        model._diff_times: {}
        model.out_net: {}
    - name: GeodesicOpt
      args:
        lr: 1e-1
      tracer: tracer
      params:
        model._kernel_locations:
          face_ids: model._kernel_face_ids
optim:
  iters: 5000
