name: "vertex-colour-texture-fitting"
tag: "${filename:${data.mesh_path}}"
exp_root_dir: "outputs"
seed: 0

data_type: known-heat-vertex-colours-datamodule
data:
  mesh_path: ../objects/spot/spot_triangulated.ply
  bake_vert_colours_if_textured: True

  sample_all_vertices: True
  num_workers: 0

  source_sampling_method: fps

trainer_type: "optimize-stationary-heat-kernels"
trainer:
  n_sources: 80
  kernel_dim: 3

  normalize_colours: False

  tracer_type: cpu-geodesic-tracer
  tracer: 
    n_debug_traces: 10

  eigen_albo: 
    k_eig: 256
    mesh_path: ${data.mesh_path}

  lrs:
    multiplier: 1.0
    centres: 1e-1
    colors: 1e-3
    anisotropies: 1e-3
    angles: 1e-3
    diff_times: 1e-3
    out_net: 0

optim:
  iters: 5000
