name: "uv-mlp-fitting"
tag: "${filename:${data.mesh_path}}"
exp_root_dir: "outputs"
seed: 0

data_type: data.uv-texture-sampler
data:
  mesh_path: ../objects/spot/spot_triangulated.obj
  bake_vert_colours_if_textured: False
  merge_tex: True
  
  batch_size: 512
  num_workers: 0
  sampling_method: "uniform"

  use_importance_sampling: False

trainer_type: trainers.uv-texture-mlp
trainer:
  network_type: modules.mlp-texture-network
  network: 
    input_dim: 3
    output_dim: 3

    width: 128
    hidden: 3

    # encoding_type: hash  
    # encoding:
    #   otype: Grid
    #   type: Hash
    #   n_levels: 10
    #   n_features_per_level: 2
    #   log2_hashmap_size: 10
    #   base_resolution: 8
    #   per_level_scale: 2
    #   interpolation: Linear

    # encoding_type: laplacian  
    # encoding:
    #   effective_k_eig: 64
    #   k_eig: 256
    #   mesh_path: ${data.mesh_path}
    #   distance_weighting: gaussian_0.05
    #   mass_type: one
    #   local_frames: principal_curvatures
    #   precompute_anisotropies: [1, 5, 15, 30, 60, 100, 200]
    #   precompute_angles_every_deg: 30

    encoding_type: positional  
    encoding:
      n_freqs: 6
      include_input: True

  loss_type: smooth_l1_loss

  optimizers:
    - name: Adam
      args: 
        lr: 1e-3

optim:
  iters: 5000
