name: "uv-texture-fitting"
tag: "${filename:${data.mesh_path}}"
exp_root_dir: "outputs"
seed: 0

data_type: data.uv-texture-sampler
data:
  mesh_path: ../objects/spot/spot_triangulated.obj
  bake_vert_colours_if_textured: False
  merge_tex: True
  
  batch_size: 64
  num_workers: 0
  sampling_method: "uniform"

trainer_type: trainers.uv-texture
trainer:
  tracer_type: modules.cpu-geodesic-tracer
  tracer: 
    n_debug_traces: 10

  eigen_albo: 
    k_eig: 256
    mesh_path: ${data.mesh_path}
    distance_weighting: gaussian_0.05

  model: 
    n_sources: 80
    kernel_dim: 32

  optimizers:
    - name: Adam
      args:
        lr: 1e-3
      params:
        model._kernel_colours: {}
        model._angles: {}
        model._anisotropies: {}
        model._diff_times: {}
        model._sharpnesses: {}
        model._opacities: {}
        model.out_net: {}
    - name: GeodesicOpt
      args:
        lr: 1e-1
      tracer: tracer
      params:
        model._kernel_locations:
          face_ids: model._kernel_face_ids
optim:
  iters: 5000
