name: "vertex-colour-texture-fitting"
tag: "${filename:${mesh.path}}"
exp_root_dir: "outputs"
seed: 0

mesh:
  path: ../objects/spot/spot_triangulated.ply
  bake_vert_colours: ${has_texture:${mesh.path}}

trainer_type: "optimise-vertex-colours"
trainer:
  n_sources: 80
  kernel_dim: 32

  normalize_colours: False

  tracer_type: cpu-geodesic-tracer
  tracer: 
    n_debug_traces: 10

  eigen_albo: 
    k_eig: 256
    mesh_path: ${mesh.path}

  lrs:
    multiplier: 1.0
    centres: 1e-1
    colors: 1e-3
    anisotropies: 1e-3
    angles: 1e-3
    diff_times: 1e-3
    out_net: 1e-3

optim:
  iters: 5000
  
data:
  batch_size: 1
  num_workers: 0
  dataset_type: "all-vertex-colours-dataset"